spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/interview?useUnicode=yes&characterEncoding=UTF8&useSSL=false&useAffectedRows=true&serverTimezone=GMT
      username: root
      password: j6>Px!7u!BWa
      initialSize: 5
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
debug: true
